### PR TITLE
Read comment please :)

### PR DESCRIPTION
**Pull request by Helpme0822**
I just did this to ask if you could maybe add a rocket launcher template please? And also maybe create a release with the exe file since idk how to compile it :D

### CODE REVIEW

**Comment by Hxrv3y** [comment]
Hey man. Thanks for the PR. If you would like templates added please make an issue not a pull request. However I will look into doing this for you

**Comment by Helpme0822** [comment]
Hi,

have you already done the rocket launcher template?

Also how do I open an issue on your project? Since I don't see the issues tab in your project.

**Comment by Hxrv3y** [comment]
> Hi,
> 
> have you already done the rocket launcher template?
> 
> Also how do I open an issue on your project? Since I don't see the issues tab in your project.

The rocket launcher template as of yet has not been done. Have been working on another project but will be done soon. Thank you

**Comment by Hxrv3y** [comment]
> I just did this to ask if you could maybe add a rocket launcher template please? And also maybe create a release with the exe file since idk how to compile it :D

Working on the rocket launcher soon. Adding the .exe file now

**Comment by Hxrv3y** [comment]
> I just did this to ask if you could maybe add a rocket launcher template please? And also maybe create a release with the exe file since idk how to compile it :D

RPG has finally been added (Not been tested as couldn't having issues) also been compiled with the release of v1.0.5

**Comment by Helpme0822** [comment]
Thank you very much

**Comment by Hxrv3y** [comment]
> Thank you very much

On latest release the error that was happening before has been fixed. (I compiled the debug not release. oops.)

**Comment by DyroS3** [comment]
@Hxrv3y Can you do Releases on the latest code?

**Comment by Hxrv3y** [comment]
> @Hxrv3y Can you do Releases on the latest code?

I have been trying to compile the latest code for a while now and no matter what I do can't manage to get WXWidgets to compile. I have been busy with other stuff also. If you would like to use the latest version, you will either have to compile yourself or ask someone to compile for you.

Sorry if this has caused any issues caused.

**Pull request closed without merging**
